version: '3'
services:
  db:
    restart: always
    container_name: coronicle_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coronicle
      MYSQL_USER: coronicle
      MYSQL_PASSWORD: coronicle
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - backend

  coronicle-be:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/coronicle?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: coronicle
      SPRING_DATASOURCE_PASSWORD: coronicle
    networks:
      - backend
    depends_on:
      - db
    ports:
      - 15000:8080

volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend: